pipeline {
  agent anysdfsdfsdfsd
  stages {
    stage('error') {
      parallel {
        stage('errordddd') {
          steps {bbb
            timeout(time: 1,  unit: 'MINUTES')
            sh '55555'
            sh 'xcvcv'
          }
        }
        stage('error') {
          steps {
            mail(subject: 'xcvxcv', body: 'xcvxcvxcv')sdfsdfsdf
          }sdfsdfsdfsdf
        }
      }
    }
    stage('dfdfd') {sfsdfsdfgdfg
      steps {
        timestamps() {
          mail(subject: 'fgdfg', body: 'dfgdfg')
        }

        mail(subject: 'fgdfg', body: 'dfgdfg')
      }
    }
  }
}
